# Generated by Django 4.1.3 on 2022-12-21 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='municipalite x', max_length=500, null=None)),
                ('zone', models.CharField(choices=[('tunis', 'tunis'), ('ariana', 'ariana'), ('nabeul', 'nabeul')], max_length=50)),
                ('slugy', models.SlugField(max_length=500)),
                ('decrisption', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='decribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=50)),
                ('text', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(default='ananymous', on_delete=django.db.models.deletion.CASCADE, to='op1.client')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=700)),
                ('date', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='op1.client')),
            ],
        ),
    ]
