# Generated by Django 4.1.3 on 2022-12-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
