# Generated by Django 4.1.3 on 2022-12-22 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0002_client_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='decribe',
            name='municipality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='op1.municipality'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='decrisption',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='slugy',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
