# Generated by Django 4.1.3 on 2022-12-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0003_decribe_municipality_alter_municipality_decrisption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='decribe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='op1.decribe'),
        ),
    ]
