# Generated by Django 4.1.3 on 2022-12-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0004_comment_decribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decribe',
            name='client',
            field=models.ForeignKey(default='ananymous', on_delete=django.db.models.deletion.CASCADE, to='op1.client'),
        ),
    ]
