# Generated by Django 4.1.3 on 2022-12-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0005_alter_decribe_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='decribe',
            name='slugy',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
