# Generated by Django 4.1.3 on 2022-12-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0006_decribe_slugy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='decribe',
            new_name='Decribe',
        ),
    ]
