# Generated by Django 4.1.3 on 2022-12-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0009_alter_comment_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='decribe_to_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(blank=True, max_length=2000, null=True)),
                ('slugy', models.SlugField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default='ananymous', on_delete=django.db.models.deletion.CASCADE, to='op1.client')),
                ('municipality', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='op1.municipality')),
            ],
        ),
    ]
