# Generated by Django 4.1.3 on 2022-12-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0010_decribe_to_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='decribe',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='municipality',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
