# Generated by Django 4.1.3 on 2022-12-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0012_remove_client_pic_remove_decribe_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='decribe',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='decribe_to_check',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='municipality',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
