# Generated by Django 4.1.3 on 2022-12-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0013_client_pic_decribe_pic_decribe_to_check_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(max_length=70, null=True),
        ),
    ]
