# Generated by Django 4.1.3 on 2022-12-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0014_alter_client_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
    ]
