# Generated by Django 4.1.3 on 2022-12-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0015_remove_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='zone',
            field=models.CharField(max_length=50),
        ),
    ]
