# Generated by Django 4.1.3 on 2023-01-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0016_alter_municipality_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decribe_to_check',
            name='pic',
            field=models.ImageField(blank=True, default='no.jfif', null=True, upload_to=''),
        ),
    ]
