# Generated by Django 4.1.3 on 2023-01-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0017_alter_decribe_to_check_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='locali',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
