# Generated by Django 4.1.3 on 2023-01-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0019_municipality_finance_municipality_gouve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decribe',
            name='admin_decribe',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='decribe',
            name='tach',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pic',
            field=models.ImageField(blank=True, default='image/no.jpg', null=True, upload_to=''),
        ),
    ]
