# Generated by Django 4.1.3 on 2023-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op1', '0022_alter_client_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pic',
            field=models.ImageField(blank='True', default='/images/picture.png', null='True', upload_to='no.jp'),
        ),
    ]
